### ISSUE TITLE
关于 ReferenceError: Cannot access 'testSite' before initialization  的报错

### ISSUE THREAD

**Issue by double-point** [mqhe2007/pmp-apply-helper#1]
运行的时候报错了，请问大佬这个应该怎么改：

(node:46620) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'testSite' before initialization
    at C:\Users\wzg\Desktop\pmp-apply-helper-main\pmp-apply-helper-main\main.js:22:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 38)
(node:46620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rickif** [comment]
遇到了同样的问题

**Comment by mqhe2007** [comment]
请拉取一下更新，再次尝试。

**Comment by rickif** [comment]
> 请拉取一下更新，再次尝试。

问题解决了
