### ISSUE TITLE
选完考场最后一步报错

### ISSUE THREAD

**Issue by eco-ryoma** [mqhe2007/pmp-apply-helper#2]
![image](https://user-images.githubusercontent.com/19233892/114734305-ae3f0700-9d76-11eb-9616-81f9858d700a.png)

报名并发1,第3次,200
类型“System.DBNull”的对象无法转换为类型“System.Int32”。
Request canceled
Request canceled
Request canceled
Request canceled
执行结束

**Comment by eco-ryoma** [comment]
大佬 如果看到问题，帮忙看是否可以修复一下，感谢

**Comment by mqhe2007** [comment]
这个问题我没有复现出来，检查一下你的config.js配置是否正确。

**Comment by rickif** [comment]
![image](https://user-images.githubusercontent.com/16649269/114796639-12d48300-9dc4-11eb-9a2b-770b383ea70f.png)
![image](https://user-images.githubusercontent.com/16649269/114796676-1ff17200-9dc4-11eb-9ea6-5eaa3f17ba66.png)

@mqhe2007 遇到了同样的问题，重试依然如此。我的配置文件大概形式如下
![image](https://user-images.githubusercontent.com/16649269/114796593-f89aa500-9dc3-11eb-9cc4-6ac4b2e3d399.png)

**Comment by eco-ryoma** [comment]
> 这个问题我没有复现出来，检查一下你的config.js配置是否正确。

![image](https://user-images.githubusercontent.com/19233892/114797539-fafdfe80-9dc5-11eb-8411-0e8c44c57f58.png)
config.js配置信息 是参照项目中示例提示 写的，类似如上图

**Comment by eco-ryoma** [comment]
![image](https://user-images.githubusercontent.com/19233892/114803129-7d3ff000-9dd1-11eb-89a7-92e9ac50d24a.png)
还是会报这个 对象转换错误

**Comment by mqhe2007** [comment]
> ![image](https://user-images.githubusercontent.com/19233892/114803129-7d3ff000-9dd1-11eb-89a7-92e9ac50d24a.png)
> 还是会报这个 对象转换错误

不好意思，我这边确实无法复现，我没有机会重试。你可以参考最新的config-template直接添加好考点配置，则可以跳过选择考点步骤（数据在文档最后一部分），再试试。
